add logs for gradlew

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,20 +1,25 @@
 name: Test
 
-run-name: ${{ github.actor }} is learning GitHub Actions
-
 on: [ push ]
 
 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
+
       - name: Ensure Gradlew exists and has executable permission
         run: |
-          ls -l ./gradlew
+          echo "Checking gradlew permissions"
+          ls -l ./gradlew || echo "gradlew not found"
           chmod +x ./gradlew
-      - uses: actions/setup-java@v4
+
+      - name: Setup Java
+        uses: actions/setup-java@v4
         with:
           distribution: 'zulu'
           java-version: '21'
-      - run: ./gradlew clean test
+
+      - name: Run tests
+        run: ./gradlew clean test
